### ISSUE TITLE
Geo no longer responding? 

### ISSUE THREAD

**Issue by Alexandra-Nicolas** [mapbox/geo-googledocs#29]
I used the script to geocode a number of addresses (600+) but I just deployed the script on a new sheet. Set it to run as usual, all the steps seem to be in order, but the new columns are not being created and then I get a "geocoding is finished" dialogue box despite nothing having happened. Thoughts?

**Comment by Grsmto** [comment]
Just to say that I ended up with something using the fork of @leighghunt using the Google geocode API here https://github.com/leighghunt/geo-googledocs/blob/patch-1/MapBox.js
