### ISSUE TITLE
Geo code receiving error message

### ISSUE THREAD

**Issue by lorrykirk** [mapbox/geo-googledocs#42]
I've been using geo codes for awhile now and love using it but recently i'm getting this error message:

UiApp has been deprecated. Please use HtmlService instead.

Can you specify?

Thanks,

Lorry

**Comment by augwich** [comment]
I've just started receiving this error as well. Too bad as this is a great script - but I don't know enough of how it's put together to know what needs to be done to fix this. Hopefully someone sees this.

**Comment by amaridev** [comment]
Having the same problem.

**Comment by roqueleal** [comment]
Same problem

**Comment by isaakd** [comment]
Same... seems to be deprecated now.

**Comment by augwich** [comment]
I will note to others running into this problem - I've been able to solve the issue by simply exporting the Google Sheets as a .csv (I have a separate sheet with functions that auto-parses out the data I actually want to export). Then you can import that .csv into Mapbox. It's not as clean of a process, but it does work while this plugin is down.

**Comment by Krukarius** [comment]
I also have the same problem

I cannot neither use geocode tool nor save as a GeoJSON file due to the info above.
Any hints how to solve it?

**Comment by hkdeven** [comment]
👍

**Comment by techieshark** [comment]
Confirming this is shown when running Geo > Geocode Addresses:

<img width="656" alt="image" src="https://user-images.githubusercontent.com/1072292/73118660-2622e500-3fab-11ea-8aac-ad78619af17a.png">

**Comment by crukundo** [comment]
Guys, any chance of this being fixed in the near future (tomorrow)?

**Comment by hkdeven** [comment]
LOL, obviously no @kollinsayz -
This has been an open issue for a year, so...

**Comment by LoganSound** [comment]
same problem

**Comment by goose2000** [comment]
2021 - script is not updated. I used Addon "Geocode by Awesome Table" - worked, no cost.
